name: test

on:
  push:
    branches:
      - gw

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: SSH-TEST
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}

          script: |
            whoami > d.txt
