name: test1

on:
  push:
    branches: [gw]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH-TEST
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          password: ${{secrets.PW}}
          port: ${{secrets.PORT}}

          script: |
            echo "2323" > d.txt

  notification:
    name: Notification
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build]
    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.check.outputs.status }}
          author_name: Github Action Bot
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
